///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class loginDataModelDataTenantStatus {
/*
{
  "desc": "正常",
  "code": "NORMAL"
}
*/

  String desc;
  String code;

  loginDataModelDataTenantStatus({
    this.desc,
    this.code,
  });
  loginDataModelDataTenantStatus.fromJson(Map<String, dynamic> json) {
    desc = json["desc"]?.toString();
    code = json["code"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["desc"] = desc;
    data["code"] = code;
    return data;
  }
}

class loginDataModelDataTenantType {
/*
{
  "desc": "创建",
  "code": "CREATE"
}
*/

  String desc;
  String code;

  loginDataModelDataTenantType({
    this.desc,
    this.code,
  });
  loginDataModelDataTenantType.fromJson(Map<String, dynamic> json) {
    desc = json["desc"]?.toString();
    code = json["code"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["desc"] = desc;
    data["code"] = code;
    return data;
  }
}

class loginDataModelDataTenant {
/*
{
  "id": "1270186482916655104",
  "createTime": "2020-06-09 10:50:31",
  "createUser": "1",
  "updateTime": "2020-06-09 10:50:31",
  "updateUser": "1",
  "code": "3201042006001",
  "identifyCode": "gzMrSD85",
  "name": "南京子屹",
  "type": {
    "desc": "创建",
    "code": "CREATE"
  },
  "status": {
    "desc": "正常",
    "code": "NORMAL"
  },
  "readonly": false,
  "duty": "冯兴磊",
  "expirationTime": null,
  "logo": "http://120.26.66.211:10000/file/2020/06/ff4b8ea4-fe56-4e68-8e96-5d32ef4639a3.png",
  "describe": "子屹智能立志用自身研发技术能力为客户提供全面的IT解决方案",
  "passwordExpire": 0,
  "isMultipleLogin": true,
  "passwordErrorNum": 10,
  "passwordErrorLockTime": "1h"
}
*/

  String id;
  String createTime;
  String createUser;
  String updateTime;
  String updateUser;
  String code;
  String identifyCode;
  String name;
  loginDataModelDataTenantType type;
  loginDataModelDataTenantStatus status;
  bool readonly;
  String duty;
  String expirationTime;
  String logo;
  String describe;
  int passwordExpire;
  bool isMultipleLogin;
  int passwordErrorNum;
  String passwordErrorLockTime;

  loginDataModelDataTenant({
    this.id,
    this.createTime,
    this.createUser,
    this.updateTime,
    this.updateUser,
    this.code,
    this.identifyCode,
    this.name,
    this.type,
    this.status,
    this.readonly,
    this.duty,
    this.expirationTime,
    this.logo,
    this.describe,
    this.passwordExpire,
    this.isMultipleLogin,
    this.passwordErrorNum,
    this.passwordErrorLockTime,
  });
  loginDataModelDataTenant.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    createTime = json["createTime"]?.toString();
    createUser = json["createUser"]?.toString();
    updateTime = json["updateTime"]?.toString();
    updateUser = json["updateUser"]?.toString();
    code = json["code"]?.toString();
    identifyCode = json["identifyCode"]?.toString();
    name = json["name"]?.toString();
    type = json["type"] != null ? loginDataModelDataTenantType.fromJson(json["type"]) : null;
    status = json["status"] != null ? loginDataModelDataTenantStatus.fromJson(json["status"]) : null;
    readonly = json["readonly"];
    duty = json["duty"]?.toString();
    expirationTime = json["expirationTime"]?.toString();
    logo = json["logo"]?.toString();
    describe = json["describe"]?.toString();
    passwordExpire = json["passwordExpire"]?.toInt();
    isMultipleLogin = json["isMultipleLogin"];
    passwordErrorNum = json["passwordErrorNum"]?.toInt();
    passwordErrorLockTime = json["passwordErrorLockTime"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["createTime"] = createTime;
    data["createUser"] = createUser;
    data["updateTime"] = updateTime;
    data["updateUser"] = updateUser;
    data["code"] = code;
    data["identifyCode"] = identifyCode;
    data["name"] = name;
    if (type != null) {
      data["type"] = type.toJson();
    }
    if (status != null) {
      data["status"] = status.toJson();
    }
    data["readonly"] = readonly;
    data["duty"] = duty;
    data["expirationTime"] = expirationTime;
    data["logo"] = logo;
    data["describe"] = describe;
    data["passwordExpire"] = passwordExpire;
    data["isMultipleLogin"] = isMultipleLogin;
    data["passwordErrorNum"] = passwordErrorNum;
    data["passwordErrorLockTime"] = passwordErrorLockTime;
    return data;
  }
}

class loginDataModelDataDeviceTerminal {
/*
{
  "id": "1273093212545744896",
  "createTime": "2020-06-17 11:20:49",
  "createEmployee": "1270186493553410048",
  "updateTime": "2020-06-17 11:20:49",
  "updateEmployee": "1270186493553410048",
  "name": "终端1",
  "code": "001",
  "ip": "192.168.1.1",
  "macAddress": "sfggsdfaa-aewqgsfdaef-aeqrtqrq1352132132-1213ads123fa1f23d",
  "isDelete": false,
  "tenantCode": "3201042006001"
}
*/

  String id;
  String createTime;
  String createEmployee;
  String updateTime;
  String updateEmployee;
  String name;
  String code;
  String ip;
  String macAddress;
  bool isDelete;
  String tenantCode;

  loginDataModelDataDeviceTerminal({
    this.id,
    this.createTime,
    this.createEmployee,
    this.updateTime,
    this.updateEmployee,
    this.name,
    this.code,
    this.ip,
    this.macAddress,
    this.isDelete,
    this.tenantCode,
  });
  loginDataModelDataDeviceTerminal.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    createTime = json["createTime"]?.toString();
    createEmployee = json["createEmployee"]?.toString();
    updateTime = json["updateTime"]?.toString();
    updateEmployee = json["updateEmployee"]?.toString();
    name = json["name"]?.toString();
    code = json["code"]?.toString();
    ip = json["ip"]?.toString();
    macAddress = json["macAddress"]?.toString();
    isDelete = json["isDelete"];
    tenantCode = json["tenantCode"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["createTime"] = createTime;
    data["createEmployee"] = createEmployee;
    data["updateTime"] = updateTime;
    data["updateEmployee"] = updateEmployee;
    data["name"] = name;
    data["code"] = code;
    data["ip"] = ip;
    data["macAddress"] = macAddress;
    data["isDelete"] = isDelete;
    data["tenantCode"] = tenantCode;
    return data;
  }
}

class loginDataModelDataToken {
/*
{
  "userId": null,
  "token": "e4b23e80ed120e61a1b633fef65dec86",
  "expire": 2592000
}
*/

  String userId;
  String token;
  int expire;

  loginDataModelDataToken({
    this.userId,
    this.token,
    this.expire,
  });
  loginDataModelDataToken.fromJson(Map<String, dynamic> json) {
    userId = json["userId"]?.toString();
    token = json["token"]?.toString();
    expire = json["expire"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["userId"] = userId;
    data["token"] = token;
    data["expire"] = expire;
    return data;
  }
}

class loginDataModelData {
/*
{
  "token": {
    "userId": null,
    "token": "e4b23e80ed120e61a1b633fef65dec86",
    "expire": 2592000
  },
  "deviceTerminal": {
    "id": "1273093212545744896",
    "createTime": "2020-06-17 11:20:49",
    "createEmployee": "1270186493553410048",
    "updateTime": "2020-06-17 11:20:49",
    "updateEmployee": "1270186493553410048",
    "name": "终端1",
    "code": "001",
    "ip": "192.168.1.1",
    "macAddress": "sfggsdfaa-aewqgsfdaef-aeqrtqrq1352132132-1213ads123fa1f23d",
    "isDelete": false,
    "tenantCode": "3201042006001"
  },
  "tenant": {
    "id": "1270186482916655104",
    "createTime": "2020-06-09 10:50:31",
    "createUser": "1",
    "updateTime": "2020-06-09 10:50:31",
    "updateUser": "1",
    "code": "3201042006001",
    "identifyCode": "gzMrSD85",
    "name": "南京子屹",
    "type": {
      "desc": "创建",
      "code": "CREATE"
    },
    "status": {
      "desc": "正常",
      "code": "NORMAL"
    },
    "readonly": false,
    "duty": "冯兴磊",
    "expirationTime": null,
    "logo": "http://120.26.66.211:10000/file/2020/06/ff4b8ea4-fe56-4e68-8e96-5d32ef4639a3.png",
    "describe": "子屹智能立志用自身研发技术能力为客户提供全面的IT解决方案",
    "passwordExpire": 0,
    "isMultipleLogin": true,
    "passwordErrorNum": 10,
    "passwordErrorLockTime": "1h"
  }
}
*/

  loginDataModelDataToken token;
  loginDataModelDataDeviceTerminal deviceTerminal;
  loginDataModelDataTenant tenant;

  loginDataModelData({
    this.token,
    this.deviceTerminal,
    this.tenant,
  });
  loginDataModelData.fromJson(Map<String, dynamic> json) {
    token = json["token"] != null ? loginDataModelDataToken.fromJson(json["token"]) : null;
    deviceTerminal = json["deviceTerminal"] != null ? loginDataModelDataDeviceTerminal.fromJson(json["deviceTerminal"]) : null;
    tenant = json["tenant"] != null ? loginDataModelDataTenant.fromJson(json["tenant"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (token != null) {
      data["token"] = token.toJson();
    }
    if (deviceTerminal != null) {
      data["deviceTerminal"] = deviceTerminal.toJson();
    }
    if (tenant != null) {
      data["tenant"] = tenant.toJson();
    }
    return data;
  }
}

class loginDataModel {
/*
{
  "code": 0,s
  "data": {
    "token": {
      "userId": null,
      "token": "e4b23e80ed120e61a1b633fef65dec86",
      "expire": 2592000
    },
    "deviceTerminal": {
      "id": "1273093212545744896",
      "createTime": "2020-06-17 11:20:49",
      "createEmployee": "1270186493553410048",
      "updateTime": "2020-06-17 11:20:49",
      "updateEmployee": "1270186493553410048",
      "name": "终端1",
      "code": "001",
      "ip": "192.168.1.1",
      "macAddress": "sfggsdfaa-aewqgsfdaef-aeqrtqrq1352132132-1213ads123fa1f23d",
      "isDelete": false,
      "tenantCode": "3201042006001"
    },
    "tenant": {
      "id": "1270186482916655104",
      "createTime": "2020-06-09 10:50:31",
      "createUser": "1",
      "updateTime": "2020-06-09 10:50:31",
      "updateUser": "1",
      "code": "3201042006001",
      "identifyCode": "gzMrSD85",
      "name": "南京子屹",
      "type": {
        "desc": "创建",
        "code": "CREATE"
      },
      "status": {
        "desc": "正常",
        "code": "NORMAL"
      },
      "readonly": false,
      "duty": "冯兴磊",
      "expirationTime": null,
      "logo": "http://120.26.66.211:10000/file/2020/06/ff4b8ea4-fe56-4e68-8e96-5d32ef4639a3.png",
      "describe": "子屹智能立志用自身研发技术能力为客户提供全面的IT解决方案",
      "passwordExpire": 0,
      "isMultipleLogin": true,
      "passwordErrorNum": 10,
      "passwordErrorLockTime": "1h"
    }
  },
  "msg": "操作成功",
  "path": null,
  "extra": null,
  "timestamp": "1592466376085",
  "isSuccess": true,
  "isError": false
}
*/

  int code;
  loginDataModelData data;
  String msg;
  String path;
  String extra;
  String timestamp;
  bool isSuccess;
  bool isError;

  loginDataModel({
    this.code,
    this.data,
    this.msg,
    this.path,
    this.extra,
    this.timestamp,
    this.isSuccess,
    this.isError,
  });
  loginDataModel.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    data = json["data"] != null&&json["data"].toString().length!=0 ? loginDataModelData.fromJson(json["data"]) : null;
    msg = json["msg"]?.toString();
    path = json["path"]?.toString();
    extra = json["extra"]?.toString();
    timestamp = json["timestamp"]?.toString();
    isSuccess = json["isSuccess"];
    isError = json["isError"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    data["msg"] = msg;
    data["path"] = path;
    data["extra"] = extra;
    data["timestamp"] = timestamp;
    data["isSuccess"] = isSuccess;
    data["isError"] = isError;
    return data;
  }
}
