///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AproveDataModel {
/*
{
  "code": 0,
  "data": true,
  "msg": "操作成功",
  "path": null,
  "extra": null,
  "timestamp": "1593767598911",
  "isSuccess": true,
  "isError": false
}
*/

  int code;
  bool data;
  String msg;
  String path;
  String extra;
  String timestamp;
  bool isSuccess;
  bool isError;

  AproveDataModel({
    this.code,
    this.data,
    this.msg,
    this.path,
    this.extra,
    this.timestamp,
    this.isSuccess,
    this.isError,
  });
  AproveDataModel.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    data = json["data"];
    msg = json["msg"]?.toString();
    path = json["path"]?.toString();
    extra = json["extra"]?.toString();
    timestamp = json["timestamp"]?.toString();
    isSuccess = json["isSuccess"];
    isError = json["isError"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    data["data"] = this.data;
    data["msg"] = msg;
    data["path"] = path;
    data["extra"] = extra;
    data["timestamp"] = timestamp;
    data["isSuccess"] = isSuccess;
    data["isError"] = isError;
    return data;
  }
}
