///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RecordModelDateDataPersonType {
/*
{
  "desc": "拜访人",
  "code": "VISITOR"
}
*/

  String desc;
  String code;

  RecordModelDateDataPersonType({
    this.desc,
    this.code,
  });
  RecordModelDateDataPersonType.fromJson(Map<String, dynamic> json) {
    desc = json["desc"]?.toString();
    code = json["code"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["desc"] = desc;
    data["code"] = code;
    return data;
  }
}

class RecordModelDateDataVisitStatus {
/*
{
  "desc": "待同意",
  "code": "WAIT_AGREE"
}
*/

  String desc;
  String code;

  RecordModelDateDataVisitStatus({
    this.desc,
    this.code,
  });
  RecordModelDateDataVisitStatus.fromJson(Map<String, dynamic> json) {
    desc = json["desc"]?.toString();
    code = json["code"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["desc"] = desc;
    data["code"] = code;
    return data;
  }
}

class RecordModelDateDataVisitMethod {
/*
{
  "desc": "名片",
  "code": "VISITING_CARD"
}
*/

  String desc;
  String code;

  RecordModelDateDataVisitMethod({
    this.desc,
    this.code,
  });
  RecordModelDateDataVisitMethod.fromJson(Map<String, dynamic> json) {
    desc = json["desc"]?.toString();
    code = json["code"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["desc"] = desc;
    data["code"] = code;
    return data;
  }
}

class RecordModelDateDataInterviewPartnerReturnDtoListPartner {
/*
{
  "key": null,
  "data": null
}
*/

  String key;
  String data;

  RecordModelDateDataInterviewPartnerReturnDtoListPartner({
    this.key,
    this.data,
  });
  RecordModelDateDataInterviewPartnerReturnDtoListPartner.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataInterviewPartnerReturnDtoList {
/*
{
  "partner": {
    "key": null,
    "data": null
  },
  "partnerTenantName": null,
  "partnerName": "朱重八",
  "partnerIdCard": "430821199301128259"
}
*/

  RecordModelDateDataInterviewPartnerReturnDtoListPartner partner;
  String partnerTenantName;
  String partnerName;
  String partnerIdCard;

  RecordModelDateDataInterviewPartnerReturnDtoList({
    this.partner,
    this.partnerTenantName,
    this.partnerName,
    this.partnerIdCard,
  });
  RecordModelDateDataInterviewPartnerReturnDtoList.fromJson(Map<String, dynamic> json) {
    partner = json["partner"] != null ? RecordModelDateDataInterviewPartnerReturnDtoListPartner.fromJson(json["partner"]) : null;
    partnerTenantName = json["partnerTenantName"]?.toString();
    partnerName = json["partnerName"]?.toString();
    partnerIdCard = json["partnerIdCard"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (partner != null) {
      data["partner"] = partner.toJson();
    }
    data["partnerTenantName"] = partnerTenantName;
    data["partnerName"] = partnerName;
    data["partnerIdCard"] = partnerIdCard;
    return data;
  }
}

class RecordModelDateDataIntervieweeDataTenantCodeDataArea {
/*
{
  "key": "430102000000",
  "data": "湖南省长沙市芙蓉区"
}
*/

  String key;
  String data;

  RecordModelDateDataIntervieweeDataTenantCodeDataArea({
    this.key,
    this.data,
  });
  RecordModelDateDataIntervieweeDataTenantCodeDataArea.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataIntervieweeDataTenantCodeData {
/*
{
  "name": "湖南敏求",
  "area": {
    "key": "430102000000",
    "data": "湖南省长沙市芙蓉区"
  }
}
*/

  String name;
  RecordModelDateDataIntervieweeDataTenantCodeDataArea area;

  RecordModelDateDataIntervieweeDataTenantCodeData({
    this.name,
    this.area,
  });
  RecordModelDateDataIntervieweeDataTenantCodeData.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    area = json["area"] != null ? RecordModelDateDataIntervieweeDataTenantCodeDataArea.fromJson(json["area"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    if (area != null) {
      data["area"] = area.toJson();
    }
    return data;
  }
}

class RecordModelDateDataIntervieweeDataTenantCode {
/*
{
  "key": "4301022007002",
  "data": {
    "name": "湖南敏求",
    "area": {
      "key": "430102000000",
      "data": "湖南省长沙市芙蓉区"
    }
  }
}
*/

  String key;
  RecordModelDateDataIntervieweeDataTenantCodeData data;

  RecordModelDateDataIntervieweeDataTenantCode({
    this.key,
    this.data,
  });
  RecordModelDateDataIntervieweeDataTenantCode.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"] != null ? RecordModelDateDataIntervieweeDataTenantCodeData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

class RecordModelDateDataIntervieweeDataStation {
/*
{
  "key": null,
  "data": null
}
*/

  String key;
  String data;

  RecordModelDateDataIntervieweeDataStation({
    this.key,
    this.data,
  });
  RecordModelDateDataIntervieweeDataStation.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataIntervieweeDataOrg {
/*
{
  "key": null,
  "data": null
}
*/

  String key;
  String data;

  RecordModelDateDataIntervieweeDataOrg({
    this.key,
    this.data,
  });
  RecordModelDateDataIntervieweeDataOrg.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataIntervieweeDataUserIdData {
/*
{
  "id": "1282941883890270208",
  "name": "万超",
  "avatar": "http://120.26.66.211:10000/file/2020/07/ce07406d-a32e-4f10-81d6-382effb9b679.jpg",
  "idCard": "430781199007282512",
  "mobile": "13307422738",
  "account": "WC27381594712155681"
}
*/

  String id;
  String name;
  String avatar;
  String idCard;
  String mobile;
  String account;

  RecordModelDateDataIntervieweeDataUserIdData({
    this.id,
    this.name,
    this.avatar,
    this.idCard,
    this.mobile,
    this.account,
  });
  RecordModelDateDataIntervieweeDataUserIdData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    avatar = json["avatar"]?.toString();
    idCard = json["idCard"]?.toString();
    mobile = json["mobile"]?.toString();
    account = json["account"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["avatar"] = avatar;
    data["idCard"] = idCard;
    data["mobile"] = mobile;
    data["account"] = account;
    return data;
  }
}

class RecordModelDateDataIntervieweeDataUserId {
/*
{
  "key": "1282941883890270208",
  "data": {
    "id": "1282941883890270208",
    "name": "万超",
    "avatar": "http://120.26.66.211:10000/file/2020/07/ce07406d-a32e-4f10-81d6-382effb9b679.jpg",
    "idCard": "430781199007282512",
    "mobile": "13307422738",
    "account": "WC27381594712155681"
  }
}
*/

  String key;
  RecordModelDateDataIntervieweeDataUserIdData data;

  RecordModelDateDataIntervieweeDataUserId({
    this.key,
    this.data,
  });
  RecordModelDateDataIntervieweeDataUserId.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"] != null ? RecordModelDateDataIntervieweeDataUserIdData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

class RecordModelDateDataIntervieweeData {
/*
{
  "id": "1285060838637436928",
  "name": "万超",
  "idCard": "430781199007282512",
  "userId": {
    "key": "1282941883890270208",
    "data": {
      "id": "1282941883890270208",
      "name": "万超",
      "avatar": "http://120.26.66.211:10000/file/2020/07/ce07406d-a32e-4f10-81d6-382effb9b679.jpg",
      "idCard": "430781199007282512",
      "mobile": "13307422738",
      "account": "WC27381594712155681"
    }
  },
  "org": {
    "key": null,
    "data": null
  },
  "station": {
    "key": null,
    "data": null
  },
  "tenantCode": {
    "key": "4301022007002",
    "data": {
      "name": "湖南敏求",
      "area": {
        "key": "430102000000",
        "data": "湖南省长沙市芙蓉区"
      }
    }
  }
}
*/

  String id;
  String name;
  String idCard;
  RecordModelDateDataIntervieweeDataUserId userId;
  RecordModelDateDataIntervieweeDataOrg org;
  RecordModelDateDataIntervieweeDataStation station;
  RecordModelDateDataIntervieweeDataTenantCode tenantCode;

  RecordModelDateDataIntervieweeData({
    this.id,
    this.name,
    this.idCard,
    this.userId,
    this.org,
    this.station,
    this.tenantCode,
  });
  RecordModelDateDataIntervieweeData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    idCard = json["idCard"]?.toString();
    userId = json["userId"] != null ? RecordModelDateDataIntervieweeDataUserId.fromJson(json["userId"]) : null;
    org = json["org"] != null ? RecordModelDateDataIntervieweeDataOrg.fromJson(json["org"]) : null;
    station = json["station"] != null ? RecordModelDateDataIntervieweeDataStation.fromJson(json["station"]) : null;
    tenantCode = json["tenantCode"] != null ? RecordModelDateDataIntervieweeDataTenantCode.fromJson(json["tenantCode"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["idCard"] = idCard;
    if (userId != null) {
      data["userId"] = userId.toJson();
    }
    if (org != null) {
      data["org"] = org.toJson();
    }
    if (station != null) {
      data["station"] = station.toJson();
    }
    if (tenantCode != null) {
      data["tenantCode"] = tenantCode.toJson();
    }
    return data;
  }
}

class RecordModelDateDataInterviewee {
/*
{
  "key": "1285060838637436928",
  "data": {
    "id": "1285060838637436928",
    "name": "万超",
    "idCard": "430781199007282512",
    "userId": {
      "key": "1282941883890270208",
      "data": {
        "id": "1282941883890270208",
        "name": "万超",
        "avatar": "http://120.26.66.211:10000/file/2020/07/ce07406d-a32e-4f10-81d6-382effb9b679.jpg",
        "idCard": "430781199007282512",
        "mobile": "13307422738",
        "account": "WC27381594712155681"
      }
    },
    "org": {
      "key": null,
      "data": null
    },
    "station": {
      "key": null,
      "data": null
    },
    "tenantCode": {
      "key": "4301022007002",
      "data": {
        "name": "湖南敏求",
        "area": {
          "key": "430102000000",
          "data": "湖南省长沙市芙蓉区"
        }
      }
    }
  }
}
*/

  String key;
  RecordModelDateDataIntervieweeData data;

  RecordModelDateDataInterviewee({
    this.key,
    this.data,
  });
  RecordModelDateDataInterviewee.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"] != null ? RecordModelDateDataIntervieweeData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

class RecordModelDateDataVisitorDataTenantCodeDataArea {
/*
{
  "key": "430102000000",
  "data": "湖南省长沙市芙蓉区"
}
*/

  String key;
  String data;

  RecordModelDateDataVisitorDataTenantCodeDataArea({
    this.key,
    this.data,
  });
  RecordModelDateDataVisitorDataTenantCodeDataArea.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataVisitorDataTenantCodeData {
/*
{
  "name": "湖南敏求",
  "area": {
    "key": "430102000000",
    "data": "湖南省长沙市芙蓉区"
  }
}
*/

  String name;
  RecordModelDateDataVisitorDataTenantCodeDataArea area;

  RecordModelDateDataVisitorDataTenantCodeData({
    this.name,
    this.area,
  });
  RecordModelDateDataVisitorDataTenantCodeData.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    area = json["area"] != null ? RecordModelDateDataVisitorDataTenantCodeDataArea.fromJson(json["area"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    if (area != null) {
      data["area"] = area.toJson();
    }
    return data;
  }
}

class RecordModelDateDataVisitorDataTenantCode {
/*
{
  "key": "4301022007002",
  "data": {
    "name": "湖南敏求",
    "area": {
      "key": "430102000000",
      "data": "湖南省长沙市芙蓉区"
    }
  }
}
*/

  String key;
  RecordModelDateDataVisitorDataTenantCodeData data;

  RecordModelDateDataVisitorDataTenantCode({
    this.key,
    this.data,
  });
  RecordModelDateDataVisitorDataTenantCode.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"] != null ? RecordModelDateDataVisitorDataTenantCodeData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

class RecordModelDateDataVisitorDataStation {
/*
{
  "key": null,
  "data": null
}
*/

  String key;
  String data;

  RecordModelDateDataVisitorDataStation({
    this.key,
    this.data,
  });
  RecordModelDateDataVisitorDataStation.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataVisitorDataOrg {
/*
{
  "key": null,
  "data": null
}
*/

  String key;
  String data;

  RecordModelDateDataVisitorDataOrg({
    this.key,
    this.data,
  });
  RecordModelDateDataVisitorDataOrg.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    data["data"] = this.data;
    return data;
  }
}

class RecordModelDateDataVisitorDataUserIdData {
/*
{
  "id": "1282967321077350400",
  "name": "何旭东",
  "avatar": "http://120.26.66.211:10000/file/4301022007002/2020/07/797ad555-5ad0-4e6a-ac4e-f821c19c5080.jpeg",
  "idCard": "421022199708291818",
  "mobile": "13974275925",
  "account": "HXD59251594718220380"
}
*/

  String id;
  String name;
  String avatar;
  String idCard;
  String mobile;
  String account;

  RecordModelDateDataVisitorDataUserIdData({
    this.id,
    this.name,
    this.avatar,
    this.idCard,
    this.mobile,
    this.account,
  });
  RecordModelDateDataVisitorDataUserIdData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    avatar = json["avatar"]?.toString();
    idCard = json["idCard"]?.toString();
    mobile = json["mobile"]?.toString();
    account = json["account"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["avatar"] = avatar;
    data["idCard"] = idCard;
    data["mobile"] = mobile;
    data["account"] = account;
    return data;
  }
}

class RecordModelDateDataVisitorDataUserId {
/*
{
  "key": "1282967321077350400",
  "data": {
    "id": "1282967321077350400",
    "name": "何旭东",
    "avatar": "http://120.26.66.211:10000/file/4301022007002/2020/07/797ad555-5ad0-4e6a-ac4e-f821c19c5080.jpeg",
    "idCard": "421022199708291818",
    "mobile": "13974275925",
    "account": "HXD59251594718220380"
  }
}
*/

  String key;
  RecordModelDateDataVisitorDataUserIdData data;

  RecordModelDateDataVisitorDataUserId({
    this.key,
    this.data,
  });
  RecordModelDateDataVisitorDataUserId.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"] != null ? RecordModelDateDataVisitorDataUserIdData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

class RecordModelDateDataVisitorData {
/*
{
  "id": "1285101800684257280",
  "name": "何旭东",
  "idCard": "421022199708291818",
  "userId": {
    "key": "1282967321077350400",
    "data": {
      "id": "1282967321077350400",
      "name": "何旭东",
      "avatar": "http://120.26.66.211:10000/file/4301022007002/2020/07/797ad555-5ad0-4e6a-ac4e-f821c19c5080.jpeg",
      "idCard": "421022199708291818",
      "mobile": "13974275925",
      "account": "HXD59251594718220380"
    }
  },
  "org": {
    "key": null,
    "data": null
  },
  "station": {
    "key": null,
    "data": null
  },
  "tenantCode": {
    "key": "4301022007002",
    "data": {
      "name": "湖南敏求",
      "area": {
        "key": "430102000000",
        "data": "湖南省长沙市芙蓉区"
      }
    }
  }
}
*/

  String id;
  String name;
  String idCard;
  RecordModelDateDataVisitorDataUserId userId;
  RecordModelDateDataVisitorDataOrg org;
  RecordModelDateDataVisitorDataStation station;
  RecordModelDateDataVisitorDataTenantCode tenantCode;

  RecordModelDateDataVisitorData({
    this.id,
    this.name,
    this.idCard,
    this.userId,
    this.org,
    this.station,
    this.tenantCode,
  });
  RecordModelDateDataVisitorData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    idCard = json["idCard"]?.toString();
    userId = json["userId"] != null ? RecordModelDateDataVisitorDataUserId.fromJson(json["userId"]) : null;
    org = json["org"] != null ? RecordModelDateDataVisitorDataOrg.fromJson(json["org"]) : null;
    station = json["station"] != null ? RecordModelDateDataVisitorDataStation.fromJson(json["station"]) : null;
    tenantCode = json["tenantCode"] != null ? RecordModelDateDataVisitorDataTenantCode.fromJson(json["tenantCode"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["idCard"] = idCard;
    if (userId != null) {
      data["userId"] = userId.toJson();
    }
    if (org != null) {
      data["org"] = org.toJson();
    }
    if (station != null) {
      data["station"] = station.toJson();
    }
    if (tenantCode != null) {
      data["tenantCode"] = tenantCode.toJson();
    }
    return data;
  }
}

class RecordModelDateDataVisitor {
/*
{
  "key": "1285101800684257280",
  "data": {
    "id": "1285101800684257280",
    "name": "何旭东",
    "idCard": "421022199708291818",
    "userId": {
      "key": "1282967321077350400",
      "data": {
        "id": "1282967321077350400",
        "name": "何旭东",
        "avatar": "http://120.26.66.211:10000/file/4301022007002/2020/07/797ad555-5ad0-4e6a-ac4e-f821c19c5080.jpeg",
        "idCard": "421022199708291818",
        "mobile": "13974275925",
        "account": "HXD59251594718220380"
      }
    },
    "org": {
      "key": null,
      "data": null
    },
    "station": {
      "key": null,
      "data": null
    },
    "tenantCode": {
      "key": "4301022007002",
      "data": {
        "name": "湖南敏求",
        "area": {
          "key": "430102000000",
          "data": "湖南省长沙市芙蓉区"
        }
      }
    }
  }
}
*/

  String key;
  RecordModelDateDataVisitorData data;

  RecordModelDateDataVisitor({
    this.key,
    this.data,
  });
  RecordModelDateDataVisitor.fromJson(Map<String, dynamic> json) {
    key = json["key"]?.toString();
    data = json["data"] != null ? RecordModelDateDataVisitorData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["key"] = key;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    return data;
  }
}

class RecordModelDateData {
/*
{
  "id": "1285856107083857920",
  "appointmentCode": "5MPiA1kn",
  "visitor": {
    "key": "1285101800684257280",
    "data": {
      "id": "1285101800684257280",
      "name": "何旭东",
      "idCard": "421022199708291818",
      "userId": {
        "key": "1282967321077350400",
        "data": {
          "id": "1282967321077350400",
          "name": "何旭东",
          "avatar": "http://120.26.66.211:10000/file/4301022007002/2020/07/797ad555-5ad0-4e6a-ac4e-f821c19c5080.jpeg",
          "idCard": "421022199708291818",
          "mobile": "13974275925",
          "account": "HXD59251594718220380"
        }
      },
      "org": {
        "key": null,
        "data": null
      },
      "station": {
        "key": null,
        "data": null
      },
      "tenantCode": {
        "key": "4301022007002",
        "data": {
          "name": "湖南敏求",
          "area": {
            "key": "430102000000",
            "data": "湖南省长沙市芙蓉区"
          }
        }
      }
    }
  },
  "visitorName": "何旭东",
  "visitorTenantName": "湖南敏求",
  "interviewee": {
    "key": "1285060838637436928",
    "data": {
      "id": "1285060838637436928",
      "name": "万超",
      "idCard": "430781199007282512",
      "userId": {
        "key": "1282941883890270208",
        "data": {
          "id": "1282941883890270208",
          "name": "万超",
          "avatar": "http://120.26.66.211:10000/file/2020/07/ce07406d-a32e-4f10-81d6-382effb9b679.jpg",
          "idCard": "430781199007282512",
          "mobile": "13307422738",
          "account": "WC27381594712155681"
        }
      },
      "org": {
        "key": null,
        "data": null
      },
      "station": {
        "key": null,
        "data": null
      },
      "tenantCode": {
        "key": "4301022007002",
        "data": {
          "name": "湖南敏求",
          "area": {
            "key": "430102000000",
            "data": "湖南省长沙市芙蓉区"
          }
        }
      }
    }
  },
  "reservationLabelId": "1285855353170296832",
  "reservationIncident": "拜访",
  "reservationTime": "2020-07-22 18:35:00",
  "partnerNumber": 1,
  "interviewPartnerReturnDtoList": [
    {
      "partner": {
        "key": null,
        "data": null
      },
      "partnerTenantName": null,
      "partnerName": "朱重八",
      "partnerIdCard": "430821199301128259"
    }
  ],
  "isSecretaryHandle": true,
  "licenseNumber": [
    1
  ],
  "visitMethod": {
    "desc": "名片",
    "code": "VISITING_CARD"
  },
  "visitStatus": {
    "desc": "待同意",
    "code": "WAIT_AGREE"
  },
  "personType": {
    "desc": "拜访人",
    "code": "VISITOR"
  },
  "showStatusName": "待同意",
  "partnerSchema": "MIDDLE"
}
*/

  String id;
  String appointmentCode;
  RecordModelDateDataVisitor visitor;
  String visitorName;
  String visitorTenantName;
  RecordModelDateDataInterviewee interviewee;
  String intervieweeName;
  String reservationLabelId;
  String reservationIncident;
  String reservationTime;
  int partnerNumber;
  List<RecordModelDateDataInterviewPartnerReturnDtoList> interviewPartnerReturnDtoList;
  bool isSecretaryHandle;
  List<String> licenseNumber;
  RecordModelDateDataVisitMethod visitMethod;
  RecordModelDateDataVisitStatus visitStatus;
  RecordModelDateDataPersonType personType;
  String showStatusName;
  String partnerSchema;

  RecordModelDateData({
    this.id,
    this.appointmentCode,
    this.visitor,
    this.visitorName,
    this.visitorTenantName,
    this.interviewee,
    this.intervieweeName,
    this.reservationLabelId,
    this.reservationIncident,
    this.reservationTime,
    this.partnerNumber,
    this.interviewPartnerReturnDtoList,
    this.isSecretaryHandle,
    this.licenseNumber,
    this.visitMethod,
    this.visitStatus,
    this.personType,
    this.showStatusName,
    this.partnerSchema,
  });
  RecordModelDateData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    appointmentCode = json["appointmentCode"]?.toString();
    visitor = json["visitor"] != null ? RecordModelDateDataVisitor.fromJson(json["visitor"]) : null;
    visitorName = json["visitorName"]?.toString();
    visitorTenantName = json["visitorTenantName"]?.toString();
    interviewee = json["interviewee"] != null ? RecordModelDateDataInterviewee.fromJson(json["interviewee"]) : null;
    intervieweeName = json["intervieweeName"]?.toString();
    reservationLabelId = json["reservationLabelId"]?.toString();
    reservationIncident = json["reservationIncident"]?.toString();
    reservationTime = json["reservationTime"]?.toString();
    partnerNumber = json["partnerNumber"]?.toInt();
    if (json["interviewPartnerReturnDtoList"] != null) {
      var v = json["interviewPartnerReturnDtoList"];
      var arr0 = List<RecordModelDateDataInterviewPartnerReturnDtoList>();
      v.forEach((v) {
        arr0.add(RecordModelDateDataInterviewPartnerReturnDtoList.fromJson(v));
      });
      interviewPartnerReturnDtoList = arr0;
    }
    isSecretaryHandle = json["isSecretaryHandle"];
    if (json["licenseNumber"] != null) {
      var v = json["licenseNumber"];
      var arr0 = List<String>();
      v.forEach((v) {
        arr0.add(v);
      });
      licenseNumber = arr0;
    }
    visitMethod = json["visitMethod"] != null ? RecordModelDateDataVisitMethod.fromJson(json["visitMethod"]) : null;
    visitStatus = json["visitStatus"] != null ? RecordModelDateDataVisitStatus.fromJson(json["visitStatus"]) : null;
    personType = json["personType"] != null ? RecordModelDateDataPersonType.fromJson(json["personType"]) : null;
    showStatusName = json["showStatusName"]?.toString();
    partnerSchema = json["partnerSchema"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["appointmentCode"] = appointmentCode;
    if (visitor != null) {
      data["visitor"] = visitor.toJson();
    }
    data["visitorName"] = visitorName;
    data["visitorTenantName"] = visitorTenantName;
    if (interviewee != null) {
      data["interviewee"] = interviewee.toJson();
    }
    data["intervieweeName"] = intervieweeName;
    data["reservationLabelId"] = reservationLabelId;
    data["reservationIncident"] = reservationIncident;
    data["reservationTime"] = reservationTime;
    data["partnerNumber"] = partnerNumber;
    if (interviewPartnerReturnDtoList != null) {
      var v = interviewPartnerReturnDtoList;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["interviewPartnerReturnDtoList"] = arr0;
    }
    data["isSecretaryHandle"] = isSecretaryHandle;
    if (licenseNumber != null) {
      var v = licenseNumber;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v);
      });
      data["licenseNumber"] = arr0;
    }
    if (visitMethod != null) {
      data["visitMethod"] = visitMethod.toJson();
    }
    if (visitStatus != null) {
      data["visitStatus"] = visitStatus.toJson();
    }
    if (personType != null) {
      data["personType"] = personType.toJson();
    }
    data["showStatusName"] = showStatusName;
    data["partnerSchema"] = partnerSchema;
    return data;
  }
}

class RecordModelDate {
/*
{
  "code": 0,
  "data": {
    "id": "1285856107083857920",
    "appointmentCode": "5MPiA1kn",
    "visitor": {
      "key": "1285101800684257280",
      "data": {
        "id": "1285101800684257280",
        "name": "何旭东",
        "idCard": "421022199708291818",
        "userId": {
          "key": "1282967321077350400",
          "data": {
            "id": "1282967321077350400",
            "name": "何旭东",
            "avatar": "http://120.26.66.211:10000/file/4301022007002/2020/07/797ad555-5ad0-4e6a-ac4e-f821c19c5080.jpeg",
            "idCard": "421022199708291818",
            "mobile": "13974275925",
            "account": "HXD59251594718220380"
          }
        },
        "org": {
          "key": null,
          "data": null
        },
        "station": {
          "key": null,
          "data": null
        },
        "tenantCode": {
          "key": "4301022007002",
          "data": {
            "name": "湖南敏求",
            "area": {
              "key": "430102000000",
              "data": "湖南省长沙市芙蓉区"
            }
          }
        }
      }
    },
    "visitorName": "何旭东",
    "visitorTenantName": "湖南敏求",
    "interviewee": {
      "key": "1285060838637436928",
      "data": {
        "id": "1285060838637436928",
        "name": "万超",
        "idCard": "430781199007282512",
        "userId": {
          "key": "1282941883890270208",
          "data": {
            "id": "1282941883890270208",
            "name": "万超",
            "avatar": "http://120.26.66.211:10000/file/2020/07/ce07406d-a32e-4f10-81d6-382effb9b679.jpg",
            "idCard": "430781199007282512",
            "mobile": "13307422738",
            "account": "WC27381594712155681"
          }
        },
        "org": {
          "key": null,
          "data": null
        },
        "station": {
          "key": null,
          "data": null
        },
        "tenantCode": {
          "key": "4301022007002",
          "data": {
            "name": "湖南敏求",
            "area": {
              "key": "430102000000",
              "data": "湖南省长沙市芙蓉区"
            }
          }
        }
      }
    },
    "reservationLabelId": "1285855353170296832",
    "reservationIncident": "拜访",
    "reservationTime": "2020-07-22 18:35:00",
    "partnerNumber": 1,
    "interviewPartnerReturnDtoList": [
      {
        "partner": {
          "key": null,
          "data": null
        },
        "partnerTenantName": null,
        "partnerName": "朱重八",
        "partnerIdCard": "430821199301128259"
      }
    ],
    "isSecretaryHandle": true,
    "licenseNumber": [
      1
    ],
    "visitMethod": {
      "desc": "名片",
      "code": "VISITING_CARD"
    },
    "visitStatus": {
      "desc": "待同意",
      "code": "WAIT_AGREE"
    },
    "personType": {
      "desc": "拜访人",
      "code": "VISITOR"
    },
    "showStatusName": "待同意",
    "partnerSchema": "MIDDLE"
  },
  "msg": "操作成功",
  "path": null,
  "extra": null,
  "timestamp": "1595407036331",
  "isSuccess": true,
  "isError": false
}
*/

  int code;
  RecordModelDateData data;
  String msg;
  String path;
  String extra;
  String timestamp;
  bool isSuccess;
  bool isError;

  RecordModelDate({
    this.code,
    this.data,
    this.msg,
    this.path,
    this.extra,
    this.timestamp,
    this.isSuccess,
    this.isError,
  });
  RecordModelDate.fromJson(Map<String, dynamic> json) {
    code = json["code"]?.toInt();
    data = json["data"] != null ? RecordModelDateData.fromJson(json["data"]) : null;
    msg = json["msg"]?.toString();
    path = json["path"]?.toString();
    extra = json["extra"]?.toString();
    timestamp = json["timestamp"]?.toString();
    isSuccess = json["isSuccess"];
    isError = json["isError"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["code"] = code;
    if (data != null) {
      data["data"] = this.data.toJson();
    }
    data["msg"] = msg;
    data["path"] = path;
    data["extra"] = extra;
    data["timestamp"] = timestamp;
    data["isSuccess"] = isSuccess;
    data["isError"] = isError;
    return data;
  }
}
